import {test} from 'node:test';import assert from 'node:assert/strict';
import {readDraft,resumeStep,mergeDraft} from '../lib/draft.ts';import {demographics,topics,SURVEY_VERSION} from '../lib/survey.ts';
test('legacy tab draft keeps all answers and exact policy progress',()=>{const answers=Object.fromEntries([...demographics,...topics.slice(0,7)].map(q=>[q.key,0]));const old=JSON.stringify({version:SURVEY_VERSION,answers,step:15,consent:true});const d=readDraft([old,null]);assert.deepEqual(d?.answers,answers);assert.equal(resumeStep(d!),15);assert.equal(d?.consent,true);});
test('persistent draft keeps choices after reopening and never loses missing older answers',()=>{const older={version:SURVEY_VERSION,answers:{demo_age:1,demo_gender:2},step:2,consent:true,updatedAt:1},newer={...older,answers:{demo_age:3},step:1,updatedAt:2};const d=readDraft([JSON.stringify(older),JSON.stringify(newer)]);assert.deepEqual(d?.answers,{demo_age:3,demo_gender:2});assert.equal(d?.step,1);});
test('malformed storage is ignored and missing demographics cannot skip Sheet A',()=>{assert.equal(readDraft(['not JSON',null]),null);const d=readDraft([JSON.stringify({version:SURVEY_VERSION,answers:{demo_age:1,demo_gender:999},step:20,consent:true})]);assert.equal(d?.answers.demo_age,1);assert.equal(d?.answers.demo_gender,undefined);assert.equal(resumeStep(d!),1);});
test('saved complete review stays on review with unchanged numeric codes',()=>{const answers=Object.fromEntries([...demographics,...topics].map(q=>[q.key,q.options.length-1]));const d=readDraft([JSON.stringify({version:SURVEY_VERSION,answers,step:28,consent:true})]);assert.equal(resumeStep(d!),28);assert.deepEqual(d?.answers,answers);});

test('stale tab cannot erase persistent answers or later progress',()=>{const active:DraftLike={version:SURVEY_VERSION,answers:{demo_age:2},step:1,consent:true,updatedAt:3};const persisted={...active,answers:{demo_age:1,demo_gender:0,q01_bailout_equity:4},step:9,updatedAt:2};const merged=mergeDraft(active,JSON.stringify(persisted));assert.deepEqual(merged.answers,{demo_age:2,demo_gender:0,q01_bailout_equity:4});assert.equal(merged.step,9);});
type DraftLike=NonNullable<ReturnType<typeof readDraft>>;
test('legacy active tab takes priority over persistent choices during upgrade',()=>{const d=readDraft([JSON.stringify({version:SURVEY_VERSION,answers:{demo_age:4},step:1,consent:true}),JSON.stringify({version:SURVEY_VERSION,answers:{demo_age:1},step:1,consent:true,updatedAt:100})]);assert.equal(d?.answers.demo_age,4);});

test('repeated stale-tab writes retain carried progress without changing live step',()=>{const stale={version:SURVEY_VERSION,answers:{demo_age:2},step:1,consent:true,updatedAt:3};const newer={...stale,answers:{demo_age:1,demo_gender:0},step:2};const first=mergeDraft(stale,JSON.stringify(newer));const second=mergeDraft(stale,JSON.stringify(first));assert.equal(first.step,2);assert.equal(second.step,2);assert.deepEqual(second.answers,first.answers);});
