import {test} from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync,readdirSync} from 'node:fs';import {stripTypeScriptTypes} from 'node:module';
const uri=source=>'data:text/javascript;base64,'+Buffer.from(stripTypeScriptTypes(source,{mode:'transform'})).toString('base64');
const deps=Object.fromEntries(['security-core','survey','analytics'].map(name=>[name,uri(readFileSync(`lib/${name}.ts`,'utf8'))]));
const fixture={SERVER_SALT:'fixture-salt-'.repeat(4),ADMIN_SECRET_KEY:'fixture-admin-'.repeat(4),APP_ORIGIN:'https://fixture.example',TRUSTED_IP_HEADER:'',DB:null};globalThis.__pollTestEnv=fixture;
let source=readFileSync('lib/server.ts','utf8').replace("const env=process.env;",'const env=globalThis.__pollTestEnv;').replace("import {getDatabase} from './database';",'const getDatabase=()=>globalThis.__pollTestEnv.DB;');for(const [key,value] of Object.entries(deps))source=source.replaceAll(`'./${key}'`,JSON.stringify(value));
const server=await import(uri(source));const {demographics,SURVEY_VERSION}=await import(deps.survey);
function setup(){const sqlite=new DatabaseSync(':memory:');sqlite.exec('PRAGMA foreign_keys=ON');for(const f of readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())sqlite.exec(readFileSync('drizzle/'+f,'utf8'));function prepare(sql){return {sql,params:[],bind(...params){return {...this,params};},first(){return sqlite.prepare(this.sql).get(...this.params)??null;},all(){return {results:sqlite.prepare(this.sql).all(...this.params)};},run(){return sqlite.prepare(this.sql).run(...this.params);}};}fixture.DB={prepare,batch(statements){sqlite.exec('BEGIN');try{const result=statements.map(s=>s.run());sqlite.exec('COMMIT');return result;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};return sqlite;}
function req(body,cookie='',csrf=''){return new Request(fixture.APP_ORIGIN+'/api/session',{method:'POST',headers:{Origin:fixture.APP_ORIGIN,'Content-Type':'application/json',Cookie:cookie,'x-survey-csrf':csrf},body:JSON.stringify(body)});}
const fingerprint='a'.repeat(64),begin={action:'begin',fingerprint,version:SURVEY_VERSION,adult:true,consent:true};
test('correct researcher passkey survives a failed-login flood',async()=>{const sqlite=setup();for(let i=0;i<35;i++)await server.endpoint(server.adminLogin)(req({password:'bad'}));const r=await server.endpoint(server.adminLogin)(req({password:fixture.ADMIN_SECRET_KEY}));assert.equal(r.status,200);sqlite.close();});
test('anonymous admission bounds rate rows and cleans expired rows',async()=>{const sqlite=setup();sqlite.prepare('INSERT INTO RateLimits VALUES (?,?,?)').run('expired',1,0);const invalid=await server.endpoint(server.session)(req({...begin,action:'bogus'}));assert.equal(invalid.status,400);assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM RateLimits').get().n,1);for(let i=0;i<1501;i++){const r=await server.endpoint(server.session)(req({action:'status',fingerprint:i.toString(16).padStart(64,'0')}));if(i===1500)assert.equal(r.status,429);}assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM RateLimits').get().n,1);sqlite.close();});
test('anonymous quota exhaustion does not block authenticated Sheet A completion',async()=>{const sqlite=setup();let r=await server.endpoint(server.session)(req(begin));assert.equal(r.status,200);const csrf=(await r.json()).csrf,cookie=r.headers.get('set-cookie').split(';')[0];for(let i=0;i<1500;i++)await server.endpoint(server.session)(req({action:'status',fingerprint:i.toString(16).padStart(64,'0')}));r=await server.endpoint(server.session)(req({action:'demographics',fingerprint,version:SURVEY_VERSION,demographics:Object.fromEntries(demographics.map(q=>[q.key,0]))},cookie,csrf));assert.equal(r.status,200);sqlite.close();});
