import {getDatabase} from './database';
const env=process.env;
import {hmac,signToken,verifyToken,subnet,validateTiming} from './security-core';
import {demographics,topics,validateAnswers,SURVEY_VERSION,LIKERT} from './survey';
import {csv, type TabRow} from './analytics';

export class HttpError extends Error{constructor(public status:number,message:string){super(message);}}
export const fail=(status:number,message:string):never=>{throw new HttpError(status,message);};
export function config(){const e=env as Record<string,unknown>;const salt=String(e.SERVER_SALT??process.env.SERVER_SALT??'');const admin=String(e.ADMIN_SECRET_KEY??process.env.ADMIN_SECRET_KEY??'');const origin=String(e.APP_ORIGIN??(process.env.VERCEL_ENV==='preview'&&process.env.VERCEL_URL?'https://'+process.env.VERCEL_URL:''));const ipHeader=String(e.TRUSTED_IP_HEADER??process.env.TRUSTED_IP_HEADER??'');if(salt.length<32||admin.length<12||salt.startsWith('replace-')||admin.startsWith('replace-')||!origin)fail(503,'The survey is temporarily unavailable. Please try again later.');return {salt,admin,origin,ipHeader};}
export function db(){return getDatabase();}
export function json(value:unknown,status=200,headers:Record<string,string>={}){return Response.json(value,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers}});}
export function endpoint(fn:(r:Request)=>Promise<Response>){return async(r:Request)=>{try{return await fn(r);}catch(e){if(e instanceof HttpError)return json({error:e.message},e.status);console.error('Polling endpoint failed',{type:e instanceof Error?e.name:'unknown'});return json({error:'We could not complete that request. Your answers have not been cleared. Please try again.'},503);}};}
export function requireOrigin(r:Request){const origin=r.headers.get('origin');const allowed=config().origin;const previewOrigins=process.env.VERCEL_ENV==='preview'?[process.env.VERCEL_URL,process.env.VERCEL_BRANCH_URL].filter((h):h is string=>!!h&&/^[a-z0-9-]+\.vercel\.app$/.test(h)).map(h=>'https://'+h):[];if(origin!==allowed&&!previewOrigins.includes(origin??''))fail(403,'Please open the survey directly and try again.');const fetchSite=r.headers.get('sec-fetch-site');if(fetchSite==='cross-site')fail(403,'Please open the survey directly and try again.');}
export async function body(r:Request){requireOrigin(r);if(!r.headers.get('content-type')?.startsWith('application/json'))fail(415,'Please send a valid survey response.');const declared=Number(r.headers.get('content-length')??0);if(declared>16384)fail(413,'That response is too large.');const reader=r.body?.getReader();if(!reader)fail(400,'Please send a valid survey response.');let size=0;const chunks:Uint8Array[]=[];while(true){const {done,value}=await reader!.read();if(done)break;size+=value.length;if(size>16384){await reader!.cancel();fail(413,'That response is too large.');}chunks.push(value);}try{const buffer=new Uint8Array(size);let offset=0;for(const c of chunks){buffer.set(c,offset);offset+=c.length;}const v=JSON.parse(new TextDecoder().decode(buffer));if(!v||typeof v!=='object'||Array.isArray(v))fail(400,'Please send a valid survey response.');return v as Record<string,unknown>;}catch(e){if(e instanceof HttpError)throw e;return fail(400,'Please send a valid survey response.');}}
export function exactKeys(value:Record<string,unknown>,keys:string[]){if(Object.keys(value).some(k=>!keys.includes(k)))fail(400,'Please refresh the survey and try again.');}
export function cookie(r:Request,name:string){return r.headers.get('cookie')?.split(';').map(s=>s.trim()).find(s=>s.startsWith(name+'='))?.slice(name.length+1)??'';}
export function setCookie(name:string,value:string,maxAge:number){const secure=config().origin.startsWith('https://')?'; Secure':'';return `${name}=${value}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${maxAge}${secure}`;}
export function fingerprint(value:unknown){if(typeof value!=='string'||!/^[a-f0-9]{64}$/.test(value))fail(400,'Please restart the survey in this browser.');return value as string;}
export function clientSubnet(r:Request){const name=config().ipHeader;if(!name)return 'unavailable';if(name!=='x-forwarded-for'||!process.env.VERCEL)fail(503,'The survey is temporarily unavailable.');return subnet(r.headers.get(name)??'');}
export async function rate(name:string,identity:string,limit:number,windowMs:number){const now=Date.now(),bucket=Math.floor(now/windowMs);const key=await hmac(config().salt,'rate',[name,identity,bucket]);const row=await db().prepare('INSERT INTO RateLimits (key,count,expires_at) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(key,(bucket+2)*windowMs).first<{count:number}>();if(row?.count&&row.count%100===1)await db().prepare('DELETE FROM RateLimits WHERE expires_at<?').bind(now).run();if((row?.count??limit+1)>limit)fail(429,'Too many attempts. Please wait a few minutes before trying again.');}
async function identifiers(r:Request,fp:string){const c=config();return {device:await hmac(c.salt,'device',[fp]),nullifier:await hmac(c.salt,'nullifier',[fp,clientSubnet(r)])};}
async function recorded(device:string,nullifier:string){return !!await db().prepare('SELECT survey_id FROM VoterNullifiers WHERE active=1 AND (device_hash=? OR nullifier_hash=?) LIMIT 1').bind(device,nullifier).first();}
export type SurveySession={id:string,fingerprint_hash:string,nullifier_hash:string,created_at:number,expires_at:number,stage:number,demographics_hash:string|null,completed_at:number|null};
async function getSession(r:Request,fp:string){const payload=await verifyToken(config().salt,'survey-session',cookie(r,'poll_session'));if(!payload||typeof payload.sid!=='string'||typeof payload.csrf!=='string')fail(401,'Your survey session expired. Start again; your browser can keep your draft.');if(r.headers.get('x-survey-csrf')!==payload!.csrf)fail(403,'Please restart the survey and try again.');const s=await db().prepare('SELECT * FROM SurveySessions WHERE id=?').bind(String(payload!.sid)).first<SurveySession>();const ids=await identifiers(r,fp);if(!s||s.fingerprint_hash!==ids.device||s.expires_at<Date.now())fail(401,'Your survey session expired. Please start again.');return {s:s!,ids};}
export async function session(r:Request){const b=await body(r);exactKeys(b,['action','fingerprint','consent','adult','version','demographics','website']);if(b.website)fail(400,'We could not accept that request.');if(!['status','begin','demographics'].includes(String(b.action)))fail(400,'Please refresh the survey and try again.');if(b.action!=='demographics')await rate('public-session-global','all',1500,600000);const fp=fingerprint(b.fingerprint),ids=await identifiers(r,fp);if(b.action==='begin')await rate('session-device',ids.device,60,600000);if(b.action!=='demographics'&&await recorded(ids.device,ids.nullifier))return json({recorded:true});if(b.action==='status')return json({recorded:false});if(b.version!==SURVEY_VERSION)fail(409,'The survey has changed. Please refresh before continuing.');
 if(b.action==='begin'){
  if(b.consent!==true)fail(400,'Please confirm that you have read the notice and agree to take part.');
  const previous=await verifyToken(config().salt,'survey-session',cookie(r,'poll_session'));if(previous&&typeof previous.sid==='string'&&typeof previous.csrf==='string'){const existing=await db().prepare('SELECT * FROM SurveySessions WHERE id=?').bind(previous.sid).first<SurveySession>();if(existing&&existing.fingerprint_hash===ids.device&&!existing.completed_at&&existing.expires_at>Date.now())return json({csrf:previous.csrf,stage:existing.stage});}
  await rate('new-session-global','all',1000,3600000);const now=Date.now(),sid=crypto.randomUUID(),csrf=crypto.randomUUID();await db().batch([db().prepare('DELETE FROM RateLimits WHERE expires_at<?').bind(now),db().prepare('DELETE FROM SurveySessions WHERE completed_at IS NULL AND created_at<?').bind(now-30*86400000),db().prepare('INSERT INTO SurveySessions (id,fingerprint_hash,nullifier_hash,created_at,expires_at,stage) VALUES (?,?,?,?,?,0)').bind(sid,ids.device,ids.nullifier,now,now+86400000)]);const token=await signToken(config().salt,'survey-session',{sid,csrf,exp:now+86400000});return json({csrf,stage:0},200,{'Set-Cookie':setCookie('poll_session',token,86400)});
 }
 if(b.action==='demographics'){const {s}=await getSession(r,fp);await rate('session-device',ids.device,60,600000);if(await recorded(ids.device,ids.nullifier))return json({recorded:true});let answers:Record<string,number>;try{answers=validateAnswers(b.demographics,demographics);}catch(e){return fail(400,(e as Error).message);}const hash=await hmac(config().salt,'demographics',[answers]);await db().prepare('UPDATE SurveySessions SET stage=1,demographics_hash=? WHERE id=? AND completed_at IS NULL').bind(hash,s.id).run();return json({stage:1});}
 return fail(400,'Please refresh the survey and try again.');
}
export async function vote(r:Request){const b=await body(r);exactKeys(b,['fingerprint','version','demographics','topics','website','consent']);if(b.website)fail(400,'We could not accept this response.');if(b.version!==SURVEY_VERSION||b.consent!==true)fail(400,'Please refresh and confirm participation before submitting.');const fp=fingerprint(b.fingerprint),{s,ids}=await getSession(r,fp);if(await recorded(ids.device,ids.nullifier))return json({recorded:true});await rate('vote-device',ids.device,8,600000);const now=Date.now();if(!validateTiming(s.created_at,now))fail(400,'Please take time to read the questions, then try submitting again.');let d:Record<string,number>,t:Record<string,number>;try{d=validateAnswers(b.demographics,demographics);t=validateAnswers(b.topics,topics);}catch(e){return fail(400,(e as Error).message);}const demoHash=await hmac(config().salt,'demographics',[d]);if(s.stage!==1||s.demographics_hash!==demoHash)fail(409,'Please finish the background section before submitting.');const surveyId=crypto.randomUUID();
 const insert=(table:string,answers:Record<string,number>)=>{const cols=Object.keys(answers);return db().prepare(`INSERT INTO ${table} (survey_id,${cols.join(',')}) VALUES (${Array(cols.length+1).fill('?').join(',')})`).bind(surveyId,...Object.values(answers));};
 try{await db().batch([db().prepare('INSERT INTO VoterNullifiers (survey_id,session_id,nullifier_hash,device_hash,active,submitted_at,duration_ms,version) SELECT ?,id,?,?,1,?,?,? FROM SurveySessions WHERE id=? AND stage=1 AND demographics_hash=? AND completed_at IS NULL').bind(surveyId,ids.nullifier,ids.device,now,now-s.created_at,SURVEY_VERSION,s.id,demoHash),insert('DemographicResponses',d),insert('TopicResponses',t),db().prepare('UPDATE SurveySessions SET completed_at=? WHERE id=?').bind(now,s.id)]);}catch(e){if(await recorded(ids.device,ids.nullifier))return json({recorded:true});throw e;}return json({recorded:true,accepted:true});
}
function equal(a:string,b:string){if(a.length!==b.length)return false;let different=0;for(let i=0;i<a.length;i++)different|=a.charCodeAt(i)^b.charCodeAt(i);return different===0;}
export async function adminSession(r:Request){const token=await verifyToken(config().admin,'admin-session',cookie(r,'poll_admin'));if(!token||typeof token.csrf!=='string')fail(401,'Sign in to view research results.');return token!;}
export async function adminLogin(r:Request){const b=await body(r);exactKeys(b,['password']);if(typeof b.password!=='string'||b.password.length>256)fail(401,'That passkey was not accepted. Try again.');const [a,x]=await Promise.all([hmac(config().salt,'password',[config().admin]),hmac(config().salt,'password',[b.password])]);if(!equal(a,x)){await rate('admin-login-global','all',30,900000);const ip=clientSubnet(r);if(ip!=='unavailable')await rate('admin-login-ip',ip,10,900000);fail(401,'That passkey was not accepted. Try again.');}const csrf=crypto.randomUUID(),token=await signToken(config().admin,'admin-session',{csrf,exp:Date.now()+28800000});return json({csrf},200,{'Set-Cookie':setCookie('poll_admin',token,28800)});}
export async function adminLogout(r:Request){requireOrigin(r);const token=await adminSession(r);if(r.headers.get('x-admin-csrf')!==token.csrf)fail(403,'Please refresh and try again.');return json({ok:true},200,{'Set-Cookie':setCookie('poll_admin','',0)});}
function selected(r:Request){const u=new URL(r.url),topic=topics.find(q=>q.key===(u.searchParams.get('topic')??topics[0].key)),demo=demographics.find(q=>q.key===(u.searchParams.get('demographic')??'demo_ideology'));if(!topic||!demo)fail(400,'Choose a valid question and background category.');return {topic:topic!,demo:demo!};}
async function grouped(topic:string,demo:string,labels:string[]):Promise<TabRow[]>{const rows=(await db().prepare(`SELECT d.${demo} AS group_value,t.${topic} AS answer,COUNT(*) AS count FROM DemographicResponses d JOIN TopicResponses t USING(survey_id) JOIN VoterNullifiers n USING(survey_id) WHERE n.active=1 GROUP BY d.${demo},t.${topic}`).all<{group_value:number,answer:number,count:number}>()).results;const groups=labels.map(label=>({label,total:0,counts:[0,0,0,0,0],percentages:[0,0,0,0,0]}));for(const r of rows){const g=groups[r.group_value];if(g&&r.answer>=0&&r.answer<5){g.counts[r.answer]=r.count;g.total+=r.count;}}return groups.map(g=>({...g,percentages:g.counts.map(n=>g.total?n/g.total*100:0)}));}
export async function metrics(r:Request){const token=await adminSession(r),{topic,demo}=selected(r);const since=Date.now()-30*86400000;const [m,starts,complete,groups,overview]=await Promise.all([db().prepare('SELECT COUNT(*) AS total,AVG(duration_ms) AS averageMs FROM VoterNullifiers WHERE active=1').first<{total:number,averageMs:number|null}>(),db().prepare('SELECT COUNT(*) AS count FROM SurveySessions WHERE created_at>=?').bind(since).first<{count:number}>(),db().prepare('SELECT COUNT(*) AS count FROM SurveySessions WHERE created_at>=? AND completed_at IS NOT NULL').bind(since).first<{count:number}>(),grouped(topic.key,demo.key,demo.options),Promise.all(topics.map(q=>db().prepare(`SELECT ${q.key} AS answer,COUNT(*) AS count FROM TopicResponses JOIN VoterNullifiers USING(survey_id) WHERE active=1 GROUP BY ${q.key}`).all<{answer:number,count:number}>().then(v=>({key:q.key,counts:LIKERT.map((_,i)=>v.results.find(r=>r.answer===i)?.count??0)}))))]);return json({csrf:token.csrf,total:m?.total??0,averageMs:m?.averageMs??null,starts:starts?.count??0,completed:complete?.count??0,completionRate:starts?.count?(complete?.count??0)/starts.count*100:null,groups,overview,version:SURVEY_VERSION,ipMode:config().ipHeader?'configured':'fingerprint-only',generatedAt:new Date().toISOString()});}
export async function exportData(r:Request){await adminSession(r);const url=new URL(r.url),kind=url.searchParams.get('kind')??'raw';let rows:unknown[][];if(kind==='raw'){const keys=[...demographics,...topics];const columns=keys.map(q=>(q.key.startsWith('demo_')?'d.':'t.')+q.key).join(',');const result=await db().prepare(`SELECT n.survey_id,n.submitted_at,n.duration_ms,n.version,${columns} FROM VoterNullifiers n JOIN DemographicResponses d USING(survey_id) JOIN TopicResponses t USING(survey_id) WHERE n.active=1 ORDER BY n.submitted_at`).all<Record<string,unknown>>();rows=[['survey_uuid','submitted_at_utc','completion_seconds','survey_version',...keys.map(q=>q.key)],...result.results.map(r=>[r.survey_id,new Date(Number(r.submitted_at)).toISOString(),Number(r.duration_ms)/1000,r.version,...keys.map(q=>q.options[Number(r[q.key])])])];}else if(kind==='crosstab'){const {topic,demo}=selected(r),groups=await grouped(topic.key,demo.key,demo.options);rows=[['question_key','question','demographic','group','group_n','answer','count','percent_within_group'],...groups.flatMap(g=>LIKERT.map((answer,i)=>[topic.key,topic.text,demo.title,g.label,g.total,answer,g.counts[i],g.total?g.percentages[i].toFixed(2):'']))];}else if(kind==='summary'){rows=[['question_key','question','answer','count','percent','total_n']];for(const q of topics){const result=await db().prepare(`SELECT t.${q.key} AS answer,COUNT(*) AS count FROM TopicResponses t JOIN VoterNullifiers n USING(survey_id) WHERE n.active=1 GROUP BY t.${q.key}`).all<{answer:number,count:number}>();const total=result.results.reduce((s,r)=>s+r.count,0);for(let i=0;i<5;i++){const count=result.results.find(r=>r.answer===i)?.count??0;rows.push([q.key,q.text,LIKERT[i],count,total?(count/total*100).toFixed(2):'',total]);}}}else return fail(400,'Choose a valid export format.');return new Response(csv(rows),{headers:{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename="civic-poll-${kind}.csv"`,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});}
